language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autotools-dev libjpeg-dev libtiff4-dev libpng12-dev libgif-dev libxt-dev autoconf automake libtool bzip2 libxml2-dev libuninameslist-dev libspiro-dev python-dev libpango1.0-dev libcairo2-dev chrpath uuid-dev
install:
  - export LIBRARY_PATH=/usr/local/lib
  - export LD_LIBRARY_PATH=/usr/local/lib
  - pushd ..
  - wget 'http://download.zeromq.org/zeromq-4.0.1.tar.gz' -O - | tar -zxf -
  - pushd zeromq-4.0.1 && ./configure && make && sudo make install && popd
  - wget 'http://download.zeromq.org/czmq-2.0.2.tar.gz' -O - |tar -zxf -
  - pushd czmq-2.0.2 && ./configure && make && sudo make install && popd 
  - wget 'https://bitbucket.org/sortsmill/libunicodenames/downloads/libunicodenames-1.1.0_beta1.tar.xz' -O - | tar -Jxf -
  - pushd libunicodenames-1.1.0_beta1 && ./configure && make && sudo make install && popd
  - wget 'http://download.savannah.gnu.org/releases/freetype/freetype-2.5.0.1.tar.gz' -O - | tar -zxf -
  - pushd freetype-2.5.0.1 && ./configure && make && sudo make install && popd
  - popd
script:
  - ./autogen.sh
  - ./configure --with-freetype-source=../freetype-2.5.0.1
  - make V=1
  - sudo make install
  - fontforge -version
branches:
  only:
    - master
